export const SET_START_QUIZ = "SET_START_QUIZ";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const SET_CURRENT_ANSWER = "SET_CURRENT_ANSWER";
export const SET_ANSWERS = "SET_ANSWERS";
export const SET_CORRECT_ANSWERS = "SET_CORRECT_ANSWERS";
export const SET_FINISH_QUIZ = "SET_FINISH_QUIZ";
export const SET_SHOW_MODAL = "SET_SHOW_MODAL";
export const SET_ERRORS = "SET_ERRORS";
